### ISSUE TITLE
-L command line option log directory override 

### ISSUE THREAD

**Issue by bryant-smith** [quadrantsec/sagan#37]
There is a `-l` option to send the sagan.log file to a separate location, bypassing the config file.  Can the `-l` be changed to redirect all logs to the new location or use `-L` for that?

**Comment by quadrantsec** [comment]
Hmmm.. I looked at the code and the $LOG_PATH is an internal variable.  It could be anything.  For example, $MY_COOL_LOG_PATH would work just as well.  Because it's not a "set" internal value,  that makes it difficult to switch with a -L command line argument.

I don't see an easy way to do this.  With that in mind, I'm gonna close it out.   You can hit me up if you want to discuss further.
