### ISSUE TITLE
meta_content fails silently when missing %sagan%

### ISSUE THREAD

**Issue by wrharding** [quadrantsec/sagan#43]
Issue:

The `meta_content` keyword does not throw an error or warning when the `%sagan%` variable does not exist.

Expected behavior:

Errors when loading a rules such as the following
```
alert any any any -> any any (msg: "TESTING RULE"; meta_content: "%sagan",apples,oranges; sid: 8686868; rev: 1;)

alert any any any -> any any (msg: "TESTING RULE"; meta_content: "sagan%",apples,oranges; sid: 8686868; rev: 1;)

alert any any any -> any any (msg: "TESTING RULE"; meta_content: "sagan",apples,oranges; sid: 8686868; rev: 1;)

alert any any any -> any any (msg: "TESTING RULE"; meta_content: "%sagn%",apples,oranges; sid: 8686868; rev: 1;)

alert any any any -> any any (msg: "TESTING RULE"; meta_content: " ",apples,oranges; sid: 8686868; rev: 1;)
```

Actual behavior:

Sagan loads find and the rule does not fire if the variable is missing, if there is a typo or if the variable is incomplete. See below.

Here is the version of Sagan I am running:
```
wharding@ruletest:~/sagan$ sagan -f sagan-wharding.yaml -l sagan.log -d engine,syslog
[*] Sagan's PID is 62562
[*] Loading classifications.conf file. [/home/wharding/sagan/sagan-rules/classification.config]
[*] 54 classifications loaded
[*] Loading references.conf file. [/home/wharding/sagan/sagan-rules/reference.config]
[*] 6 references loaded.
[*] Loading protocol map file. [/home/wharding/sagan/sagan-rules/protocol.map]
[*] 0 protocols loaded. Loaded 0 'message' search items and 0 'program' items.
[*] Loading /home/wharding/sagan/sagan-rules/normalization.rulebase for normalization.
[*] Loading included file '/home/wharding/sagan/sagan-wharding-rules.yaml'.
[*] Loading /home/wharding/sagan/sagan-rules/wharding.rules rule file.
[*] Configuration file sagan-wharding.yaml loaded and 1 rules loaded.
[*] There are 1 rules loaded.
[*] 0 flexbit(s) are in use.
[*] 0 xbit(s) are in use.
[*] 0 dynamic rule(s) are loaded.
[*] Named pipe/FIFO input type: Pipe
[*] Parse log for JSON        : Enabled
[*] Client Stats              : Disabled
[*] Syslog batch:             : 1
[*] PCRE JIT                  : Enabled
[*] 
[*] Sagan version 2.1.0 is firing up on default_sensor_name (cluster: default_cluster_name)
[*] 
[*] Not dropping privileges.  Already running as a non-privileged user
[*] ---------------------------------------------------------------------------
[*] Initializing shared memory objects.
[*] ---------------------------------------------------------------------------
[*] - Counters shared object (reload)
[*] - Xbit shared object reloaded (0 xbits loaded / max: 10000).
[*] - Flexbit shared object reloaded (0 flexbits loaded / max: 10000).
[*] - Threshold shared object reloaded (0 sources loaded / max: 10000).
[*] - After shared object reloaded (0 sources loaded / max: 10000).
[*] 
[*]  ,-._,-. 	-*> Sagan! <*-
[*]  \/)"(\/	Version 2.1.0
[*]   (_o_)	Champ Clark III & The Quadrant InfoSec Team [quadrantsec.com]
[*]   /   \/)	Copyright (C) 2009-2022 Quadrant Information Security, et al.
[*]  (|| ||) 	Using PCRE version: 8.39 2016-06-14
[*]   oo-oo
[*] 
[*] Spawning 100 Processor Threads.
[*] 
[*] Attempting to open syslog FIFO (/home/wharding/sagan/sagan-wharding.fifo).
[*] Successfully opened FIFO (/home/wharding/sagan/sagan-wharding.fifo).
[*] FIFO capacity is 65536 bytes.  Changing to 1048576 bytes.
```

Debug output:
```
[D] [input-plugins/fifo.c, line 150] [batch position 0] Raw log: 127.0.0.1|user|info|info|127.0.0.1|2022-08-05T15:09:11Z|2022-08-05T11:09:04Z|test_app| apples

[W] FIFO writer closed.  Waiting for FIFO writer to restart....
[D] [processor.c, line 157] [batch position 0] Raw log: 127.0.0.1|user|info|info|127.0.0.1|2022-08-05T15:09:11Z|2022-08-05T11:09:04Z|test_app| apples

[D] [processor.c, line 203] **[Parsed Syslog]*********************************
[D] [processor.c, line 204] Host: 127.0.0.1 | Program: test_app | Facility: user | Priority: info | Level: info | Tag: 127.0.0.1 | Date: 2022-08-05T15:09:11Z | Time: 2022-08-05T11:09:04Z
[D] [processor.c, line 205] Parsed message:  apples
```

**Comment by quadrantsec** [comment]
Thanks for reporting this !!
________________________________
From: William Harding ***@***.***>
Sent: Friday, August 5, 2022 12:29:32 PM
To: quadrantsec/sagan ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [quadrantsec/sagan] meta_content fails silently when missing %sagan% (Issue #43)


Issue:

The meta_content keyword does not throw an error or warning when the %sagan% variable does not exist.

Expected behavior:

Errors when loading a rules such as the following

alert any any any -> any any (msg: "TESTING RULE"; meta_content: "%sagan",apples,oranges; sid: 8686868; rev: 1;)

alert any any any -> any any (msg: "TESTING RULE"; meta_content: "sagan%",apples,oranges; sid: 8686868; rev: 1;)

alert any any any -> any any (msg: "TESTING RULE"; meta_content: "sagan",apples,oranges; sid: 8686868; rev: 1;)

alert any any any -> any any (msg: "TESTING RULE"; meta_content: "%sagn%",apples,oranges; sid: 8686868; rev: 1;)

alert any any any -> any any (msg: "TESTING RULE"; meta_content: " ",apples,oranges; sid: 8686868; rev: 1;)


Actual behavior:

Sagan loads find and the rule does not fire if the variable is missing, if there is a typo or if the variable is incomplete. See below.

Here is the version of Sagan I am running:

***@***.***:~/sagan$ sagan -f sagan-wharding.yaml -l sagan.log -d engine,syslog
[*] Sagan's PID is 62562
[*] Loading classifications.conf file. [/home/wharding/sagan/sagan-rules/classification.config]
[*] 54 classifications loaded
[*] Loading references.conf file. [/home/wharding/sagan/sagan-rules/reference.config]
[*] 6 references loaded.
[*] Loading protocol map file. [/home/wharding/sagan/sagan-rules/protocol.map]
[*] 0 protocols loaded. Loaded 0 'message' search items and 0 'program' items.
[*] Loading /home/wharding/sagan/sagan-rules/normalization.rulebase for normalization.
[*] Loading included file '/home/wharding/sagan/sagan-wharding-rules.yaml'.
[*] Loading /home/wharding/sagan/sagan-rules/wharding.rules rule file.
[*] Configuration file sagan-wharding.yaml loaded and 1 rules loaded.
[*] There are 1 rules loaded.
[*] 0 flexbit(s) are in use.
[*] 0 xbit(s) are in use.
[*] 0 dynamic rule(s) are loaded.
[*] Named pipe/FIFO input type: Pipe
[*] Parse log for JSON        : Enabled
[*] Client Stats              : Disabled
[*] Syslog batch:             : 1
[*] PCRE JIT                  : Enabled
[*]
[*] Sagan version 2.1.0 is firing up on default_sensor_name (cluster: default_cluster_name)
[*]
[*] Not dropping privileges.  Already running as a non-privileged user
[*] ---------------------------------------------------------------------------
[*] Initializing shared memory objects.
[*] ---------------------------------------------------------------------------
[*] - Counters shared object (reload)
[*] - Xbit shared object reloaded (0 xbits loaded / max: 10000).
[*] - Flexbit shared object reloaded (0 flexbits loaded / max: 10000).
[*] - Threshold shared object reloaded (0 sources loaded / max: 10000).
[*] - After shared object reloaded (0 sources loaded / max: 10000).
[*]
[*]  ,-._,-.    -*> Sagan! <*-
[*]  \/)"(\/    Version 2.1.0
[*]   (_o_)     Champ Clark III & The Quadrant InfoSec Team [quadrantsec.com]
[*]   /   \/)   Copyright (C) 2009-2022 Quadrant Information Security, et al.
[*]  (|| ||)    Using PCRE version: 8.39 2016-06-14
[*]   oo-oo
[*]
[*] Spawning 100 Processor Threads.
[*]
[*] Attempting to open syslog FIFO (/home/wharding/sagan/sagan-wharding.fifo).
[*] Successfully opened FIFO (/home/wharding/sagan/sagan-wharding.fifo).
[*] FIFO capacity is 65536 bytes.  Changing to 1048576 bytes.


Debug output:

[D] [input-plugins/fifo.c, line 150] [batch position 0] Raw log: 127.0.0.1|user|info|info|127.0.0.1|2022-08-05T15:09:11Z|2022-08-05T11:09:04Z|test_app| apples

[W] FIFO writer closed.  Waiting for FIFO writer to restart....
[D] [processor.c, line 157] [batch position 0] Raw log: 127.0.0.1|user|info|info|127.0.0.1|2022-08-05T15:09:11Z|2022-08-05T11:09:04Z|test_app| apples

[D] [processor.c, line 203] **[Parsed Syslog]*********************************
[D] [processor.c, line 204] Host: 127.0.0.1 | Program: test_app | Facility: user | Priority: info | Level: info | Tag: 127.0.0.1 | Date: 2022-08-05T15:09:11Z | Time: 2022-08-05T11:09:04Z
[D] [processor.c, line 205] Parsed message:  apples
