### ISSUE TITLE
Centos 7 - protocol.map error: 'type' not specified at line 1

### ISSUE THREAD

**Issue by egargale** [quadrantsec/sagan#44]
On an Centos 7 box with updated build-utils installed (yum groupinstall "Development Tools") I have the following error compiling sagan from source
```bash
./configure
make
```
error:
```
make  all-recursive
make[1]: Entering directory `/root/sagan'
Making all in src
make[2]: Entering directory `/root/sagan/src'
gcc -DHAVE_CONFIG_H -I. -I..  -I.. -I/usr/include/libfastjson    -I/usr/local/include  -g -O2 -D__Linux__ -MT sagan-sagan.o -MD -MP -MF .deps/sagan-sagan.Tpo -c -o sagan-sagan.o `test -f 'sagan.c' || echo './'`sagan.c
sagan.c: In function ‘main’:
sagan.c:1184:13: error: ‘for’ loop initial declarations are only allowed in C99 mode
             for (size_t z = 0; z != globbuf.gl_pathc; ++z)
             ^
sagan.c:1184:13: note: use option -std=c99 or -std=gnu99 to compile your code
make[2]: *** [sagan-sagan.o] Error 1
make[2]: Leaving directory `/root/sagan/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/sagan'
make: *** [all] Error 2
```
Make Version: GNU Make 3.82 Built for x86_64-redhat-linux-gnu
I got success in compiling if I do
```
make CFLAGS=-std=c99
```
check sagan compilation
```
sagan -h

--[Sagan version 2.1.0 | Help/usage screen]--------------------------------

-h, --help		Help (this screen).
-C, --credits		Sagan credits.
-d, --debug [type]	Types: engine, syslog, load, external, threads, ipc, limits, malformed, xbit, flexbit, brointel, parse_ip, client-stats, track-clients, normalize, json.
-D, --daemon		Make process a daemon (fork to the background).
-u, --user [username]	Run as user (defaults to 'sagan').
-c, --chroot [dir]	Chroot Sagan to specified directory.
-f, --config [file]	Sagan configuration file to load.
-F, --file [file]	FIFO over ride.  This reads a file in rather than reading
			from a FIFO.  The file must be in the Sagan format!
-l, --log [file]	sagan.log location [default: /var/log/sagan/sagan.log].
-Q, --quiet		Run Sagan in 'quiet' mode (no console output)
-t, --threads [#]	Set number of threads to use (overrides the sagan.yaml).
-r, --rules [file]	Use a specific rule set (overrides the sagan.yaml).
-T, --test		Test configuration (sagan.yaml) and rule sets.

* liblognorm (log normalization) support is included.
* libfastjson support is included.
* Syslog output is included.
* Using PCRE JIT.

* Compiled on Aug  7 2022 at 14:54:28.
```
Then installed sagan-rules as per [documentation](https://sagan.readthedocs.io/en/latest/install.html#post-installation-setup-and-testing)
**but**  ```run sagan --debug syslog,engine``` or ```sagan -T``` gives the error below.
``` 
[*] Loading protocol map file. [/usr/local/etc/sagan-rules/protocol.map]
[E] [protocol-map.c, line 104] 'type' not specified at line 1
```
I checked line 104 of protocol-map.c and it seems and error of decoding JSON -> C struct while reading file protocol.map
``` c
 while(fgets(mapbuf, 1024, mapfile) != NULL)
        {
            /* Skip comments and blank linkes */
            if (mapbuf[0] == '#' || mapbuf[0] == 10 || mapbuf[0] == ';' || mapbuf[0] == 32)
                {
                    line_number++;
                    continue;
                }
            else
                {
                    line_number++;
                    json_obj = json_tokener_parse(mapbuf);
                    if (json_object_object_get_ex(json_obj, "type", &tmp))
                        {
                            type = json_object_get_string(tmp);
                        }
                    else
                        {
                            Sagan_Log(ERROR, "[%s, line %d] 'type' not specified at line %d", __FILE__, __LINE__, line_number );
                        }
```
I thought of outdated Centos libraries and then I compiled and installed an updated version of **libfastjson** from ```git clone https://github.com/rsyslog/libfastjson.git ``` and also compiled and re-installed **liblognorm** from source
```
libfastjson: make check
============================================================================
Testsuite summary for libfastjson 1.2101.0.master
============================================================================
# TOTAL: 17
# PASS:  17
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
liblognorm: make check
============================================================================
Testsuite summary for liblognorm 2.0.7.master
============================================================================
# TOTAL: 115
# PASS:  115
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
```
Then I compiled again sagan pointing to the new libraries (libfastjson compiles in standard /usr dir)
```
make clean
./configure --with-lognorm-includes=/usr/local/include --with-lognorm-libraries=/usr/local/lib 
make CFLAGS=-std=c99
make install
sagan -T 
```
The error is still there:
```
[*] *******************************************************************************
[*] ** Running Sagan in 'test'. Engine will not start after testing is complete. **
[*] *******************************************************************************
[*] Sagan's PID is 9646
[*] Loading classifications.conf file. [/usr/local/etc/sagan-rules/classification.config]
[*] 53 classifications loaded
[*] Loading references.conf file. [/usr/local/etc/sagan-rules/reference.config]
[*] 6 references loaded.
[*] Loading protocol map file. [/usr/local/etc/sagan-rules/protocol.map]
[E] [protocol-map.c, line 104] 'type' not specified at line 1
```
Any help would be appreciated.

**Comment by quadrantsec** [comment]
Thank you.. I'll look at this ASAP
________________________________
From: Enrico Gargale ***@***.***>
Sent: Sunday, August 7, 2022 9:58:53 AM
To: quadrantsec/sagan ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [quadrantsec/sagan] Centos 7 - protocol.map error: 'type' not specified at line 1 (Issue #44)


On an Centos 7 box with updated build-utils installed (yum groupinstall "Development Tools") I have the following error compiling sagan from source

./configure

make

error:

make  all-recursive

make[1]: Entering directory `/root/sagan'

Making all in src

make[2]: Entering directory `/root/sagan/src'

gcc -DHAVE_CONFIG_H -I. -I..  -I.. -I/usr/include/libfastjson    -I/usr/local/include  -g -O2 -D__Linux__ -MT sagan-sagan.o -MD -MP -MF .deps/sagan-sagan.Tpo -c -o sagan-sagan.o `test -f 'sagan.c' || echo './'`sagan.c

sagan.c: In function ‘main’:

sagan.c:1184:13: error: ‘for’ loop initial declarations are only allowed in C99 mode

             for (size_t z = 0; z != globbuf.gl_pathc; ++z)

             ^

sagan.c:1184:13: note: use option -std=c99 or -std=gnu99 to compile your code

make[2]: *** [sagan-sagan.o] Error 1

make[2]: Leaving directory `/root/sagan/src'

make[1]: *** [all-recursive] Error 1

make[1]: Leaving directory `/root/sagan'

make: *** [all] Error 2



Make Version: GNU Make 3.82 Built for x86_64-redhat-linux-gnu
I got success in compiling if I do

make CFLAGS=-std=c99



check sagan compilation

sagan -h



--[Sagan version 2.1.0 | Help/usage screen]--------------------------------



-h, --help              Help (this screen).

-C, --credits           Sagan credits.

-d, --debug [type]      Types: engine, syslog, load, external, threads, ipc, limits, malformed, xbit, flexbit, brointel, parse_ip, client-stats, track-clients, normalize, json.

-D, --daemon            Make process a daemon (fork to the background).

-u, --user [username]   Run as user (defaults to 'sagan').

-c, --chroot [dir]      Chroot Sagan to specified directory.

-f, --config [file]     Sagan configuration file to load.

-F, --file [file]       FIFO over ride.  This reads a file in rather than reading

                        from a FIFO.  The file must be in the Sagan format!

-l, --log [file]        sagan.log location [default: /var/log/sagan/sagan.log].

-Q, --quiet             Run Sagan in 'quiet' mode (no console output)

-t, --threads [#]       Set number of threads to use (overrides the sagan.yaml).

-r, --rules [file]      Use a specific rule set (overrides the sagan.yaml).

-T, --test              Test configuration (sagan.yaml) and rule sets.



* liblognorm (log normalization) support is included.

* libfastjson support is included.

* Syslog output is included.

* Using PCRE JIT.



* Compiled on Aug  7 2022 at 14:54:28.



Then installed sagan-rules as per documentation<https://sagan.readthedocs.io/en/latest/install.html#post-installation-setup-and-testing>
but run sagan --debug syslog,engine or sagan -T gives the error below.

[*] Loading protocol map file. [/usr/local/etc/sagan-rules/protocol.map]

[E] [protocol-map.c, line 104] 'type' not specified at line 1



I checked line 104 of protocol-map.c and it seems and error of decoding JSON -> C struct while reading file protocol.map

 while(fgets(mapbuf, 1024, mapfile) != NULL)

        {

            /* Skip comments and blank linkes */

            if (mapbuf[0] == '#' || mapbuf[0] == 10 || mapbuf[0] == ';' || mapbuf[0] == 32)

                {

                    line_number++;

                    continue;

                }

            else

                {

                    line_number++;

                    json_obj = json_tokener_parse(mapbuf);

                    if (json_object_object_get_ex(json_obj, "type", &tmp))

                        {

                            type = json_object_get_string(tmp);

                        }

                    else

                        {

                            Sagan_Log(ERROR, "[%s, line %d] 'type' not specified at line %d", __FILE__, __LINE__, line_number );

                        }

I thought of outdated Centos libraries and then I compiled and installed an updated version of libfastjson from git clone https://github.com/rsyslog/libfastjson.git and also compiled and re-installed liblognorm from source

libfastjson: make check

============================================================================

Testsuite summary for libfastjson 1.2101.0.master

============================================================================

# TOTAL: 17

# PASS:  17

# SKIP:  0

# XFAIL: 0

# FAIL:  0

# XPASS: 0

# ERROR: 0

============================================================================

liblognorm: make check

============================================================================

Testsuite summary for liblognorm 2.0.7.master

============================================================================

# TOTAL: 115

# PASS:  115

# SKIP:  0

# XFAIL: 0

# FAIL:  0

# XPASS: 0

# ERROR: 0



Then I compiled again sagan pointing to the new libraries (libfastjson compiles in standard /usr dir)

make clean

./configure --with-lognorm-includes=/usr/local/include --with-lognorm-libraries=/usr/local/lib

make CFLAGS=-std=c99

make install

sagan -T



The error is still there:

[*] *******************************************************************************

[*] ** Running Sagan in 'test'. Engine will not start after testing is complete. **

[*] *******************************************************************************

[*] Sagan's PID is 9646

[*] Loading classifications.conf file. [/usr/local/etc/sagan-rules/classification.config]

[*] 53 classifications loaded

[*] Loading references.conf file. [/usr/local/etc/sagan-rules/reference.config]

[*] 6 references loaded.

[*] Loading protocol map file. [/usr/local/etc/sagan-rules/protocol.map]

[E] [protocol-map.c, line 104] 'type' not specified at line 1



Any help would be appreciated.

**Comment by Mrknowledge** [comment]
encountered the same problem

**Comment by quadrantsec** [comment]
Are you running the rule sets from https://github.com/quadrantsec/sagan-rules?  The protocol.map is now in JSON.

**Comment by quadrantsec** [comment]
Also,  is this from Git or Stable?

**Comment by quadrantsec** [comment]
Make sure your using the sagan and sagan-rules from github.
