### ISSUE TITLE
json_content SegFault without json_parse_data

### ISSUE THREAD

**Issue by bryant-smith** [quadrantsec/sagan#51]
Rules using `json_content` without `json_parse_data: enabled` in the yaml file will produce a SegFault.  This only seems to happen once Sagan see json logs.  If `json_parse_data` is enabled then there is no SegFault.

```
[Switching to Thread 0x7ffdd4bf6700 (LWP 35603)]
0x000055555556dc52 in JSON_Content (rule_position=rule_position@entry=0, JSON_LOCAL=JSON_LOCAL@entry=0x0)
    at json-content.c:55
55      json-content.c: No such file or directory.
(gdb) bt
#0  0x000055555556dc52 in JSON_Content (rule_position=rule_position@entry=0, JSON_LOCAL=JSON_LOCAL@entry=0x0)
    at json-content.c:55
#1  0x0000555555585f2c in Sagan_Engine (SaganProcSyslog_LOCAL=SaganProcSyslog_LOCAL@entry=0x7ffd98000b60,
    JSON_LOCAL=JSON_LOCAL@entry=0x0, dynamic_rule_flag=false) at processors/engine.c:656
#2  0x000055555556d63d in Processor () at processor.c:224
#3  0x00007ffff7aafea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#4  0x00007ffff79dfdef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by quadrantsec** [comment]
Here's what I did and hopefully it holds.  

Sagan does a check to make sure either its a) "input" is set to JSON. b) "json-parse-data" is enabled.  It neither are enabled,  it will now throw an error at startup:

```
[E] [rules.c, line 2269] Signature in /home/champ/test/test.rules at line 27 contains 'json_pcre', but the
Sagan 'input-type' isn't JSON and 'json-parse-data' is not enabled.  Abort.
```

The only place the check does NOT take place is with ```json_map```.   The reason is that if JSON is _not_ enabled,  we want the signature to act as a normal Sagan signature.  If JSON mapping _is_ enabled,  then,  if the keys are available,  it will map as specified. 

Now, the execution doesn't make it to a point a fault can take place. 

Please test and let me know if you run into any issues.  If you do, please re-open this ticket!
